### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by h1rule** [landave/TSIdentityTool#2]
`fuckedup@ubuntu:~/TSIdentityTool# gcc TSIdentityTool.c -o TSIdentityTool -l tommath -l tomcrypt
TSIdentityTool.c: In function ‘obfuscateInplace’:
TSIdentityTool.c:63:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < dataSize; i++) {
   ^
TSIdentityTool.c:63:3: note: use option -std=c99 or -std=gnu99 to compile your code
TSIdentityTool.c:76:12: error: redefinition of ‘i’
   for (int i = 0; i < 20; i++) {
            ^
TSIdentityTool.c:63:12: note: previous definition of ‘i’ was here
   for (int i = 0; i < dataSize; i++) {
            ^
TSIdentityTool.c:76:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 20; i++) {
   ^
TSIdentityTool.c: In function ‘deObfuscateInplace’:
TSIdentityTool.c:93:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < 20; i++) {
   ^
TSIdentityTool.c:98:12: error: redefinition of ‘i’
   for (int i = 0; i < dataSize; i++) {
            ^
TSIdentityTool.c:93:12: note: previous definition of ‘i’ was here
   for (int i = 0; i < 20; i++) {
            ^
TSIdentityTool.c:98:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < dataSize; i++) {
   ^
TSIdentityTool.c: In function ‘parseIni’:
TSIdentityTool.c:282:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < counter_len; i++) {
   ^
TSIdentityTool.c:288:15: error: redefinition of ‘i’
   for (size_t i = 0; i < identity_len; i++) {
               ^
TSIdentityTool.c:282:15: note: previous definition of ‘i’ was here
   for (size_t i = 0; i < counter_len; i++) {
               ^
TSIdentityTool.c:288:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < identity_len; i++) {
   ^
`

**Comment by landave** [comment]
As the error message says, you are expected to add the `-std=c99` option:
`gcc TSIdentityTool.c -std=c99 -o TSIdentityTool -l tommath -l tomcrypt`
Note that with more recent versions of gcc this option is not necessary anymore.

**Comment by h1rule** [comment]
Thanks, this worked!
