### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by gbzret4d** [landave/TSIdentityTool#5]
Hello,
i have no clue how to compile it for myself on my linux system.
Can you give me a how-to what command i need to paste?

best regards

**Comment by SapuSeven** [comment]
There are literally step-by-step instructions in the readme

**Comment by landave** [comment]
As SapuSeven said, the readme should answer your question.

**Comment by ghost** [comment]
@skapytek I pushed a win64 build from the latest commit in this project (or better said the latest fork) to my fork. You can get it here if you're still interested: https://github.com/NoTeefy/TSIdentityTool/releases

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/67905913-e050af00-fb6a-11e9-810c-327cfde96669.png)

**Comment by ghost** [comment]
Weird, thought I've included the tomlibs. Gonna need to take a look at it again tomorrow. Works for me though :>

EDIT: Oh.. I actually used my dynamic libraries when building 🤷‍♂ Gonna upload a proper version tomorrow then

**Comment by ghost** [comment]
@skapytek @Bluscream Well this took quite a while.. I totally forgot about it. I also want to apologize for bumping such an old issue. You can find the statically linked file right here: https://github.com/NoTeefy/TSIdentityTool/releases/tag/v1.0.0

Best regards
