### ISSUE TITLE
read inidentity.ini

### ISSUE THREAD

**Issue by Sharingisnotillegal** [landave/TSIdentityTool#8]
So... What's the inidentity.ini supposed to be? Whats the path it is found in ts3? There's no default file with this name, and trying to create it myself then reading it using the information found in ts3clientui_qt.secrets.conf does not provide any success.
Same with exporting a profile under 'identities'

Thanks in advance, sorry if I missed something obvious

Should edit:
The file generated with this tool is not able to be read using
./TSIdentityTool read outidentity.ini

Is this intended?

**Comment by landave** [comment]
We always refer to the ini files that TeamSpeak can import/export. If you go to Tools->Identities, you can right click on an identity to export it.
